# Generated by Django 5.2.7 on 2025-12-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless_mail', '0033_make_mail_tenant_required'),
        ('tenants', '0003_create_default_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mailrule',
            name='paperless_mail_mailrule_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='mailrule',
            name='paperless_mail_mailrule_name_unique',
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='mailrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
    ]
