# Generated by Django 5.2.7 on 2025-12-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1080_merge_tenant_and_workflow_migrations'),
        ('tenants', '0003_create_default_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='correspondent',
            name='documents_correspondent_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='correspondent',
            name='documents_correspondent_name_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='documenttype',
            name='documents_documenttype_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='documenttype',
            name='documents_documenttype_name_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='storagepath',
            name='documents_storagepath_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='storagepath',
            name='documents_storagepath_name_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='documents_tag_unique_name_owner',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='documents_tag_name_uniq',
        ),
        migrations.AlterField(
            model_name='correspondent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='document',
            name='checksum',
            field=models.CharField(editable=False, help_text='The checksum of the original document.', max_length=32, verbose_name='checksum'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='storagepath',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
    ]
